version: "3"
services:
  webserver:
    build:
      context: .
    volumes:
      - .:/var/www/app:rw
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 9000:80
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stimetable
      MYSQL_USER: root
      MYSQL_PASSWORD: root